name: "arr"
services:
  qbittorrent:
    image: "11notes/qbittorrent:5.1.1"
    read_only: true
    environment:
      TZ: "Europe/Zurich"
    volumes:
      - "qbittorrent.etc:/qbittorrent/etc"
      - "qbittorrent.var:/qbittorrent/var"
      - "share:/share"
    ports:
      - "3000:3000/tcp"
    networks:
      frontend:
    restart: "always"

volumes:
  qbittorrent.etc:
  qbittorrent.var:
  share:
    driver_opts:
      type: "nfs"
      o: "addr=share.nfs.domain.com,nolock,soft,nfsvers=4"
      device: ":/share"

networks:
  frontend: