name: "arr"
services:
  qbittorrent:
    image: "11notes/qbittorrent:5.1.2"
    read_only: true
    environment:
      TZ: "Europe/Zurich"
    volumes:
      - "qbittorrent.etc:/qbittorrent/etc"
      - "qbittorrent.var:/qbittorrent/var"
    ports:
      - "3000:3000/tcp"
      - "6881:6881/tcp"
      - "6881:6881/udp"
    networks:
      frontend:
    restart: "always"

volumes:
  qbittorrent.etc:
  qbittorrent.var:

networks:
  frontend: